### ISSUE TITLE
Build fails with "depfile has multiple output paths"

### ISSUE THREAD

**Issue by mrigger** [rampantpixels/rpmalloc#77] opened 2018-11-03 11:23 UTC
I'm trying to build rpmalloc on Ubuntu 18.04 with Ninja 1.8.2 using the following commands:
```
wget -O - https://github.com/rampantpixels/rpmalloc/archive/1.3.1.tar.gz | tar xz
cd rpmalloc-1.3.1 && python3 configure.py && ninja
```

Unexpectedly, the Ninja build fails:

```
[1/48] MKDIR lib/linux/debug
[2/48] MKDIR lib/linux/release
[3/48] MKDIR 'lib/linux/debug/b'\''x86_64'\'''
[4/48] MKDIR 'lib/linux/release/b'\''x86_64'\'''
[5/48] MKDIR bin/linux/debug
[6/48] MKDIR 'bin/linux/debug/b'\''x86_64'\'''
[7/48] CC rpmalloc/malloc.c
FAILED: build/ninja/linux/debug/b'x86_64'/rpmalloc-a8e50b6/malloc-53b207c.o 
clang -MMD -MT 'build/ninja/linux/debug/b'\''x86_64'\''/rpmalloc-a8e50b6/malloc-53b207c.o' -MF 'build/ninja/linux/debug/b'\''x86_64'\''/rpmalloc-a8e50b6/malloc-53b207c.o'.d -I.  -DRPMALLOC_COMPILE=1 -funit-at-a-time -fstrict-aliasing -fno-math-errno -ffinite-math-only -funsafe-math-optimizations -fno-trapping-math -ffast-math -D_GNU_SOURCE=1 -W -Werror -pedantic -Wall -Weverything -Wno-padded -Wno-documentation-unknown-command -std=c11  -DBUILD_DEBUG=1 -g -DENABLE_PRELOAD=1 -c rpmalloc/malloc.c -o 'build/ninja/linux/debug/b'\''x86_64'\''/rpmalloc-a8e50b6/malloc-53b207c.o'
depfile has multiple output paths[8/48] CC rpmalloc/malloc.c

FAILED: build/ninja/linux/release/b'x86_64'/rpmalloc-a8e50b6/malloc-53b207c.o 
clang -MMD -MT 'build/ninja/linux/release/b'\''x86_64'\''/rpmalloc-a8e50b6/malloc-53b207c.o' -MF 'build/ninja/linux/release/b'\''x86_64'\''/rpmalloc-a8e50b6/malloc-53b207c.o'.d -I.  -DRPMALLOC_COMPILE=1 -funit-at-a-time -fstrict-aliasing -fno-math-errno -ffinite-math-only -funsafe-math-optimizations -fno-trapping-math -ffast-math -D_GNU_SOURCE=1 -W -Werror -pedantic -Wall -Weverything -Wno-padded -Wno-documentation-unknown-command -std=c11  -DBUILD_RELEASE=1 -O3 -g -funroll-loops -DENABLE_PRELOAD=1 -c rpmalloc/malloc.c -o 'build/ninja/linux/release/b'\''x86_64'\''/rpmalloc-a8e50b6/malloc-53b207c.o'
depfile has multiple output paths[9/48] CXX rpmalloc/new.cc

FAILED: build/ninja/linux/release/b'x86_64'/rpmalloc-a8e50b6/new-440206f.o 
clang++ -MMD -MT 'build/ninja/linux/release/b'\''x86_64'\''/rpmalloc-a8e50b6/new-440206f.o' -MF 'build/ninja/linux/release/b'\''x86_64'\''/rpmalloc-a8e50b6/new-440206f.o'.d -I.  -DRPMALLOC_COMPILE=1 -funit-at-a-time -fstrict-aliasing -fno-math-errno -ffinite-math-only -funsafe-math-optimizations -fno-trapping-math -ffast-math -D_GNU_SOURCE=1 -W -Werror -pedantic -Wall -Weverything -Wno-padded -Wno-documentation-unknown-command -std=gnu++14  -DBUILD_RELEASE=1 -O3 -g -funroll-loops -DENABLE_PRELOAD=1 -c rpmalloc/new.cc -o 'build/ninja/linux/release/b'\''x86_64'\''/rpmalloc-a8e50b6/new-440206f.o'
depfile has multiple output paths[10/48] CC rpmalloc/rpmalloc.c
...
```
Do you have any idea what the problem could be?

**Comment by MJansson** [comment] 2018-11-17 10:57
Seems to be an issue when using python 3,  I can reproduce it and will fix asap.

Meanwhile try using python 2.x if possible to configure

**Comment by mrigger** [comment] 2018-11-17 11:09
Thanks a lot! Using Python 2 worked for me as you suggested.

**Comment by MJansson** [comment] 2019-01-30 11:59
Hopefully fixed now for Python 3 while keeping compatibility with Python 2

**Closed** 2019-02-03 19:12 UTC
